remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: [Eli P Fenichel]
description: [Knobloch Family Professor of Natural Resource Economics
  Yale School of the Environment]
